### ISSUE TITLE
extend vscode version compat

### ISSUE THREAD

**Issue by dezren39** [uiua-lang/uiua-vscode#1]
hello! i have some version of vscode insiders and can't install it's 'incompatible'. i'm hoping there isn't any specific reason it's not allowed and that you could extend the allowed version down as far as compatible and then also any version larger?

![image](https://github.com/uiua-lang/uiua-vscode/assets/11225574/d41db3e3-e34c-45c2-b40f-9df0daaf8a2b)
i'm not sure which way my particular issue is. v1.77.1

**Comment by kaikalii** [comment]
Yep, looks like the extension has
```
  "engines": {
    "vscode": "^1.81.0"
  },
```
in the `package.json`.

This is actually the first vscode extension I've made.
I'm not actually sure what the proper semver to put there would be.
Maybe just `"vscode": "^1"`?

**Comment by dezren39** [comment]
yeah i think something like that may work! or literally "*" too. it's a regular package.json so can also pass a space-separated list   "vscode": ">=1.81.0 <2.0.0"

**Comment by dezren39** [comment]
ah, * 'works' but immediately causes an issue because of compatiblity issues with versions less than 1.0.0. I've submitted a PR for >= 1.0.0
