### ISSUE TITLE
Semantic color customs leak to other languages

### ISSUE THREAD

**Issue by qexat** [uiua-lang/uiua-vscode#14]
## Description

The semantic token color customizations - as defined [here](https://github.com/uiua-lang/uiua-vscode/blob/main/package.json#L45-L63) - are not constrained to the Uiua language. This has the effect of defining its configuration on top of the other languages as well, for any theme that does not override the specified semantic tokens by itself.

## Example

When I'm writing a Python file with my theme [Rosalie](https://github.com/qexat/rosalie), the imported modules are colored as `#d7be8c`, instead of `#B7892E`.
![Screenshot of some Python code. A pop-up of the editor tokens and scopes inspector is visible, showing that the color of the module "typing" is user-defined and incorrect.](https://github.com/uiua-lang/uiua-vscode/assets/43090614/b0155a03-8fb0-4f76-b76e-b3facedfaecc)

Note that the editor tokens and scopes inspector reports the override as "User settings", but it means the Uiua extension really. 

## Workarounds

- Have the theme to override this extension definitions[^1]: not desirable, especially given that a user might not be the author of said theme
- Uninstall the Uiua extension: even less desirable, if one wishes to enjoy its features (and I do!) 

## Suggested fix

I have not tested this fix and I am not sure if it will do, but I'd suggest to move [the block that defines the semantic token color customizations](https://github.com/uiua-lang/uiua-vscode/blob/main/package.json#L45-L63) inside the [`[uiua]` block above](https://github.com/uiua-lang/uiua-vscode/blob/main/package.json#L38-L44).

[^1]: It might not even work, as it is dependent on the extension loading order

**Comment by kaikalii** [comment]
Unfortunately, `editor.semanticTokenColorCustomizations` is not allowed under language-specific configuration defaults, as far as I can tell.
I'm not sure how other languages do this.
I will rename the `module` token to `uiua_module`, similar to the existing `uiua_number` and `uiua_string`.

**Comment by kaikalii** [comment]
The change is made and the extension is published.
Please let me know if it fixes your issue.

**Comment by qexat** [comment]
> The change is made and the extension is published. Please let me know if it fixes your issue.

This seems to fix it. Thanks!

> Unfortunately, `editor.semanticTokenColorCustomizations` is not allowed under language-specific configuration defaults, as far as I can tell.

I think that it should be allowed. I'll look at the bug tracker of VS Code to see what is possible to do :+1:
