### ISSUE TITLE
Cannot see "ghost" inline/inlay hints or live results next to the code in VSCodium

### ISSUE THREAD

**Issue by ShinryakuTako** [uiua-lang/uiua-vscode#15]
As seen in this video @ 0:25:30 https://www.youtube.com/live/FqfXTNp5hJc?t=1530 (Tacit Talk Episode 1)

But when I try it, the `8` after `+ 3 5` or the array after `⇡10` does not appear.

I am using VSCodium on macOS. I created a new VSC profile and installed the extension by manually downloading the VSIX from the VS Code Marketplace. uiua is running in the VSC Terminal.

"Format on Save" is enabled.

**Comment by kaikalii** [comment]
Are inlay hints enabled in your settings?

**Comment by ShinryakuTako** [comment]
Yes, all the settings were at their defaults. I even tried reducing the "Inline Hint Min Length" to 1

The color highlighting and glyph auto-formatting are working.

**Comment by kaikalii** [comment]
What version of Uiua are you on?

**Comment by ShinryakuTako** [comment]
0.14.0-dev.2
All versions are the latest.

Could you create a new user profile of VSCode/ium with the bare minimum extensions and settings needed to enable all the Uiua features, and zip that over? :)

**Comment by kaikalii** [comment]
I don't think so. It's very odd though. Do you have inlay hints for other languages?

**Comment by ShinryakuTako** [comment]
I only code for Godot/GDScript in VSCodium, so I'm not sure… Are "inlay hints" provided by a setting or some other extension?

Like I said, I'm using a fresh VSCode profile, just for Uiua. Can you make a fresh profile with nothing but the Uiua extension and see if inlay hints work for you?

**Comment by kaikalii** [comment]
How do I do that? I don't use profiles. I use the same settings for everything.

**Comment by ShinryakuTako** [comment]
https://code.visualstudio.com/docs/editor/profiles

It creates a new set of settings, and profiles can be shared. A new profile should basically act as a fresh install of VSCode/ium.

**Comment by ShinryakuTako** [comment]
Well, I created a new macOS user account, downloaded new copies of the latest versions of VSCodium, Uiua, and the Uiua VSCode extension… and the inlay hints worked!

So there's something on my current user account/profile side. Let me see now…

**Comment by ShinryakuTako** [comment]
WORKAROUND?: I think I have narrowed down the problem:

❌ In VSCodium (and I assume VSCode too), if I open a Uiua workspace/file that is in iCloud Drive, like `/Users/Me/Library/Mobile Documents/com~apple~CloudDocs/Development/Uiua` then inlay hints DO NOT WORK.

✅ If I open a Uiua workspace/file in `/Users/Me/Local/Uiua` then inlay hints WORK!

CAUSE OF BUG?: **So maybe either VSC, Uiua or the extension cannot handle `~` in the path, or they cannot handle files on iCloud Drive?**

**Comment by AviKav** [comment]
A space in the filename or folder path also causes the issue

**Comment by kaikalii** [comment]
Fixed in https://github.com/uiua-lang/uiua/commit/ce04ff232d8dd71a873936161a286b1ea57d6bee.
