### ISSUE TITLE
"Ambiguous" character highlight

### ISSUE THREAD

**Issue by wackbyte** [uiua-lang/uiua-vscode#3]
Would it be possible for the extension to disable VSCode's "ambiguous character" highlighting for primitives?

When the "Unicode Highlight: Ambiguous Characters" setting is enabled, VSCode highlights some of the characters used by primitives:
![image](https://github.com/uiua-lang/uiua-vscode/assets/29505620/48e5456a-126d-4e62-b8a8-1f93b059c537)

Currently, you can add the following option to your `settings.json` to disable all of such highlighting in Uiua files:
```json
"[uiua]": {
  "editor.unicodeHighlight.ambiguousCharacters": false
}
```
However, this is inconvenient and disables highlighting in strings, which might be undesirable for some.

**Comment by kaikalii** [comment]
That's funny. In developing Uiua, I didn't notice it highlighting those because I had already told vscode to disable highlighting them when I was picking the glyphs.
Fixed in d9ff6d8. Should be deployed soon.
