### ISSUE TITLE
Support glyph input

### ISSUE THREAD

**Issue by mainrs** [uiua-lang/uiua-vscode#7]
Maybe this can be done using auto completion features of VSCode?

**Comment by kaikalii** [comment]
This goes against my vision for Uiua. The main way of entering glyphs is by typing their names and formatting.

**Comment by mainrs** [comment]
Would it be possible for the extension to then register the `uiua fmt` command as a "format on save" action? As of know, VSCode does not know that the extension is capable of formatting the code.
