### ISSUE TITLE
Error Starting client failed

### ISSUE THREAD

**Issue by Fabus1184** [uiua-lang/uiua-vscode#8]
VSCode suddenly fails to launch the uiua language server, I don't know what changed.

Output:
```
[Error - 12:54:29 AM] Starting client failed
Launching server using command uiua failed.
```

Message box pops up saying "Couldn't start client Uiua Language Server".

Reinstalled uiua and the extension but didn't change anything. Uiua itself still works.

**Comment by kaikalii** [comment]
Hm, it still works for me.
`uiua` is available in your `PATH`?

**Comment by Fabus1184** [comment]
Oh that's it, ~/.cargo/bin somehow vanished from whatever PATH VSCode is launched with, very weird… 🤔
Works now, thanks!
